pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r * public/ 2>/dev/null || true
    - rm -rf public/public
    - rm -f public/.gitlab-ci.yml
  artifacts:
    paths:
      - public
  only:
    - main



# cleaner
# pages:
#   script:
#     - mkdir public
#     - cp index.html public/
#     - cp -r css public/ 2>/dev/null || true
#     - cp -r js public/ 2>/dev/null || true
#     - cp -r images public/ 2>/dev/null || true
#     # Add any other folders/files you need
#   artifacts:
#     paths:
#       - public
#   only:
#     - master
