site_name: Nagini
site_url: https://pointcarre-app.github.io/nagini/
repo_url: https://github.com/pointcarre-app/nagini
repo_name: pointcarre-app/nagini
edit_uri: ""
docs_dir: "docs"
site_dir: "site"
copyright: "Copyright &copy; 2025 SAS POINTCARRE.APP"

theme:
  name: material
  logo: assets/logo.png
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

extra_css:
  - assets/custom.css

plugins:
  - search
  - sociale
  - git-revision-date-localized:
      type: timeago
      locale: en
      enable_creation_date: true
      exclude:
        - index.md
  - mkdocs-simple-hooks:
      hooks:
        on_config: "docs.scripts.hooks:on_config"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - API Reference: api-reference.md
  - Repository Reference:
    - Overview: repo_reference/index.md
    - nagini.js: repo_reference/nagini.md
    - utils/validation.js: repo_reference/validation.md
    - utils/createBlobWorker.js: repo_reference/createBlobWorker.md
    - pyodide/manager/manager.js: repo_reference/manager.md
    - pyodide/manager/manager-static-execution.js: repo_reference/manager-static-execution.md
    - pyodide/manager/manager-input.js: repo_reference/manager-input.md
    - pyodide/manager/manager-fs.js: repo_reference/manager-fs.md
    - pyodide/worker/worker.js: repo_reference/worker.md
    - pyodide/worker/worker-handlers.js: repo_reference/worker-handlers.md
    - pyodide/worker/worker-execution.js: repo_reference/worker-execution.md
    - pyodide/worker/worker-input.js: repo_reference/worker-input.md
    - pyodide/worker/worker-fs.js: repo_reference/worker-fs.md
    - pyodide/worker/worker-config.js: repo_reference/worker-config.md
    - pyodide/file-loader/file-loader.js: repo_reference/file-loader.md
    - pyodide/python/pyodide_init.py: repo_reference/pyodide-init.md
    - pyodide/python/capture_system.py: repo_reference/capture-system.md
    - pyodide/python/code_transformation.py: repo_reference/code-transformation.md
    - pyodide/python/pyodide_utilities.py: repo_reference/pyodide-utilities.md
    - brython/manager/manager.js: repo_reference/brython-manager.md
    - brython/manager/loader.js: repo_reference/brython-loader.md
    - brython/manager/executor.js: repo_reference/brython-executor.md
  - Third-Party Licenses: 3RD-PARTY.md 